dist: trusty
language: java
jdk:
- oraclejdk8
install:
  mvn clean test org.apache.maven.plugins:maven-deploy-plugin:2.8:deploy --settings deploy.settings.xml -DdeployAtEnd=true
notifications:
  email:
    on_success: change
    on_failure: change

cache:
  directories:
  - $HOME/.m2
  
  
