/*
 * generated by Xtext 2.20.0
 */
package simpleui.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.util.ResourceHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import simpleui.Application

@ExtendWith(InjectionExtension)
@InjectWith(SimpleUILanguageInjectorProvider)
class SimpleUILanguageHelperTest {
    def void loadModel() {
    }
}
