/*
 * generated by Xtext 2.20.0
 */
package simpleui

import org.eclipse.xtext.linking.ILinkingService

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SimpleUILanguageRuntimeModule extends AbstractSimpleUILanguageRuntimeModule {
    override Class<? extends ILinkingService> bindILinkingService() {
        SimpleUILinkingService
    }
    
    override bindILinker() {
        SimpleUILinker
    }
    
}
