/*
 * generated by Xtext 2.20.0
 */
package simpleui


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SimpleUILanguageStandaloneSetup extends SimpleUILanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new SimpleUILanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
