/*
 * generated by Xtext 2.20.0
 */
package simpleui.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class SimpleUILanguageWebModule extends AbstractSimpleUILanguageWebModule {
}
