SET @start='2017-07-01';
SET @end='2017-08-01';
SELECT date_series.ref_date, COUNT(bugs.id) FROM (
    SELECT ADDDATE(@start,t2.i*100 + t1.i*10 + t0.i) ref_date FROM
         (SELECT 0 i UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) t0,
         (SELECT 0 i UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) t1,
         (SELECT 0 i UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) t2,
         (SELECT @num:=-1) init
    ) date_series 
    LEFT JOIN bugs ON (bugs.open_date <= ref_date AND (bugs.close_date IS NULL OR bugs.close_date >= ref_date))
WHERE ref_date BETWEEN @start AND @end GROUP BY ref_date HAVING COUNT(bugs.id) > 0;
